// <auto-generated />
namespace MVC_Booking_App.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class TicketQuota : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TicketQuota));
        
        string IMigrationMetadata.Id
        {
            get { return "202506050245043_TicketQuota"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
